// Extracts ability names/descriptions, type names and per-species types/abilities
// from a local English Origin HeartGold v4.0.3 ROM into src/core/generated-extras.ts.
// Usage: npm run build && node scripts/generate-extras.mjs /path/to/origin.nds
import {readFile, writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {readNdsFile, readNarcMembers} from '../dist/core/rom.js';

const romPath = process.argv[2];
if (!romPath) throw new Error('Usage: node scripts/generate-extras.mjs <English Origin v4.0.3 ROM>');
const rom = new Uint8Array(await readFile(romPath));
const sha = b => createHash('sha256').update(b).digest('hex');

const PERSONAL_HASH = '5652a964195ceb34ed60deb021158ed8ef301c1b479c94098b9e5fb325bb7c34';
const personalArchive = readNdsFile(rom, 'a/0/0/2');
if (sha(personalArchive) !== PERSONAL_HASH) throw new Error('Unexpected personal data: not English Origin v4.0.3.');

const PUNCT = {0x1de:' ',0x1ab:'!',0x1ac:'?',0x1ad:',',0x1ae:'.',0x1af:'…',0x1b1:'/',0x1b2:'‘',0x1b3:'’',0x1b4:'“',0x1b5:'”',
  0x1b9:'(',0x1ba:')',0x1bb:'♂',0x1bc:'♀',0x1bd:'+',0x1be:'-',0x1bf:'*',0x1c0:'#',0x1c1:'=',0x1c2:'&',0x1c3:'~',0x1c4:':',0x1c5:';',
  0x1d0:'@',0x1d2:'%',0xe000:' ',0x25bc:' ',0x25bd:' '};

/** Same cipher as item-names.ts, but tolerant: line breaks become spaces, unknown glyphs are dropped. */
function readBank(bytes) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const count = view.getUint16(0, true), seed = view.getUint16(2, true);
  const out = [];
  for (let i = 0; i < count; i++) {
    const half = (seed * 0x2fd * (i + 1)) & 0xffff, key = (half | half << 16) >>> 0;
    const offset = (view.getUint32(4 + i * 8, true) ^ key) >>> 0, length = (view.getUint32(8 + i * 8, true) ^ key) >>> 0;
    let cipher = (0x91bd3 * (i + 1)) & 0xffff, text = '';
    for (let j = 0; j < length; j++) {
      const code = view.getUint16(offset + j * 2, true) ^ cipher;
      cipher = (cipher + 0x493d) & 0xffff;
      if (code === 0xffff) break;
      if (code >= 0x121 && code <= 0x12a) text += String.fromCharCode(48 + code - 0x121);
      else if (code >= 0x12b && code <= 0x144) text += String.fromCharCode(65 + code - 0x12b);
      else if (code >= 0x145 && code <= 0x15e) text += String.fromCharCode(97 + code - 0x145);
      else if (code >= 0x15f && code <= 0x19e) text += String.fromCharCode(192 + code - 0x15f);
      else if (PUNCT[code] !== undefined) text += PUNCT[code];
    }
    out.push(text.replace(/\s+/g, ' ').trim());
  }
  return out;
}

const banks = readNarcMembers(readNdsFile(rom, 'a/0/2/7'));
const abilityNames = readBank(banks[711]);
const abilityText = readBank(banks[712]);
const typeNames = readBank(banks[724]);
if (abilityNames.length < 300 || typeNames.length !== 18 || typeNames[9] !== 'Fairy') throw new Error('Unexpected text banks.');

const usable = s => /[A-Za-z]/.test(s);
const abilities = abilityNames.map((name, id) => id > 0 && usable(name) ? [name, abilityText[id] ?? ''] : null);
const personal = readNarcMembers(personalArchive).map(r => {
  const u16 = o => r[o] | r[o + 1] << 8;
  // types, abilities 1/2/hidden, gender ratio, base friendship
  return [r[6], r[7], u16(22), u16(24), u16(26), r[16], r[18]];
});
// Level-up learnsets: u16 level, u16 move, terminated by level 0xFFFF. Level 0 = learned on evolution.
const learnsets = readNarcMembers(readNdsFile(rom, 'a/0/3/3')).map(m => {
  const dv = new DataView(m.buffer, m.byteOffset, m.byteLength), out = [];
  for (let o = 0; o + 4 <= m.length; o += 4) {
    const level = dv.getUint16(o, true), move = dv.getUint16(o + 2, true);
    if (level === 0xffff) break;
    out.push(level, move);
  }
  return out;
});
if (learnsets.length !== personal.length) throw new Error('Learnset count does not match personal data.');

const payload = {types: typeNames, abilities, personal, learnsets};
const record = {gameVersion: 'origin-heartgold-english-v4.0.3', sources: {
  'a/0/0/2': PERSONAL_HASH, 'a/0/2/7#711': sha(banks[711]), 'a/0/2/7#712': sha(banks[712]), 'a/0/2/7#724': sha(banks[724]), 'a/0/3/3': sha(readNdsFile(rom, 'a/0/3/3')),
}, payload};
const output = '/** Generated by scripts/generate-extras.mjs from a local English Origin v4.0.3 ROM; do not hand edit. */\n' +
  'export interface OriginExtras { gameVersion: string; sources: Record<string, string>; payload: { types: string[]; abilities: ([string, string] | null)[]; personal: [number, number, number, number, number, number, number][]; learnsets: number[][] } }\n' +
  'export const extras: OriginExtras = ' + JSON.stringify(record) + ';\n';
await writeFile(new URL('../src/core/generated-extras.ts', import.meta.url), output);
console.log(`Wrote ${abilities.filter(Boolean).length} abilities, ${typeNames.length} types, ${personal.length} personal rows, ${learnsets.length} learnsets.`);
