"""Turn guide/*.md into Starlight pages under site/src/content/docs/guide/.

guide/ stays the single source: edit the Markdown there, then rerun this script.
What the conversion adds for the website:
- frontmatter (title, sidebar order) instead of the H1;
- links between chapters rewritten to relative site URLs (works under any base path);
- each quest (H2) wrapped in <section class="quest"> with data-* tags read from its heading,
  so the page script can filter by starter / gender and hide post-game entries;
- a location link under each quest heading, when the place before the colon is a known area;
- the "*Source:*" paragraphs (script files, flags, line numbers) folded into a <details class="tech"> box,
  hidden from players and from site search (shown with ?tech=1, see site/public/ohg.js);
- pictures: guide/images/ is copied to site/src/content/docs/guide/images/, so Astro optimises them;
  write `![what it shows](images/<name>.jpg)` in the guide (the alt text is the caption for screen readers);
- inline solvers: a line `<!-- solver: NAME -->` (on its own line, indented like the text around it)
  becomes the matching Astro component from site/src/components/ at that spot (see SOLVERS).
  On GitHub the marker is an invisible HTML comment; put it right after the guide's own answer
  (table or text), which stays on the page as the no-JavaScript fallback. A page with a marker is
  written as .mdx (with the import and the text escaped for MDX); every other page stays .md.

    python3 work/tools/site/sync_guide.py           # write
    python3 work/tools/site/sync_guide.py --check   # exit 1 if a page would change
    python3 work/tools/site/sync_guide.py --all-mdx # test: write every page as .mdx (then build and compare)
"""
import argparse
import filecmp
import html
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
GUIDE = os.path.join(REPO, 'guide')
IMAGES = os.path.join(GUIDE, 'images')
OUT = os.path.join(REPO, 'site', 'src', 'content', 'docs', 'guide')
AREAS = os.path.join(REPO, 'site', 'src', 'data', 'areas.json')

ALIASES = os.path.join(HERE, 'area_aliases.json')

STARTERS = ('Charmander', 'Pikachu', 'Bulbasaur')
# Bare heading ids that were shared by two quest pages when Done ticks were keyed by heading id alone.
LEGACY_SHARED_IDS = {'small-extras'}
GEN_NOTE = '{/* Generated by work/tools/site/sync_guide.py from guide/%s. Edit the source file, not this page. */}'

# Inline solvers: marker name -> component in site/src/components/ (imported from site/src/content/docs/guide/).
SOLVERS = {
    'celadon-password': 'CeladonPassword',
    'primo-passwords': 'PrimoPasswords',
    'janine-picker': 'JaninePicker',
    'forest-route': 'ForestRoute',
}
SOLVER_RE = re.compile(r'^([ \t]*)<!--\s*solver:\s*([A-Za-z0-9_-]+)\s*-->\s*$')
SOLVER_SLOT = '\x00solver:%s\x00'


def page_slug(fn):
    base = fn[:-3]
    if base == 'README':
        return 'index'
    return re.sub(r'^\d+-', '', base)


def page_order(fn):
    m = re.match(r'^(\d+)-', fn)
    if m:
        return int(m.group(1))
    return 0 if fn == 'README.md' else 99


POSTGAME_RE = re.compile(r"^(post-game|after the final hall of fame|after lance's visit)\b")
OTHERS_RE = re.compile(r'\bothers?\b|\bother starters?\b')


def _segments(h):
    """The heading's parentheses, split into their comma/semicolon-separated phrases."""
    segs = []
    for paren in re.findall(r'\(([^)]*)\)', h):
        segs += [s.strip() for s in re.split(r'[;,]', paren) if s.strip()]
    return segs


def heading_tags(h):
    """Tags from the quest heading's parentheses. Only explicit restrictions of the WHOLE quest hide it.

    A starter or gender phrase counts only when it is a whole phrase of its own: "(Charmander starters)",
    "(Pikachu starters only)", "(non-Pikachu starters)", "(male players)". A phrase that restricts only a
    part or a reward ("Charizardite for Charmander starters") doesn't tag the quest, and neither does a
    heading that also names what other players get ("... (Charmander starters) / ... (others)").
    "Post-game" means after the FINAL Hall of Fame: "post-game", "after the final Hall of Fame",
    "after Lance's visit". "After your first Hall of Fame" is not post-game.
    """
    tags = {}
    segs = _segments(h)
    low = [s.lower().replace('\u2019', "'") for s in segs]
    starters_alt = '|'.join(STARTERS)
    if not any(OTHERS_RE.search(s) for s in low):
        for s in segs:
            m = re.fullmatch(r'non-(%s) starters?(?: only)?' % starters_alt, s)
            if m:
                tags['starter'] = [x for x in STARTERS if x != m.group(1)]
                break
            m = re.fullmatch(r'((?:%s)(?:(?: / | or | and |, )(?:%s))*) starters?(?: only)?' % (starters_alt, starters_alt), s)
            if m:
                tags['starter'] = [x for x in STARTERS if re.search(r'\b%s\b' % x, m.group(1))]
                break
    for s in low:
        m = re.fullmatch(r'(male|female|boy|girl) players?(?: only)?', s)
        if m:
            tags['gender'] = ['male' if m.group(1) in ('male', 'boy') else 'female']
            break
    if any(re.search(r'missable|one chance', s) for s in low):
        tags['missable'] = True
    if any(POSTGAME_RE.match(s) for s in low):
        tags['postgame'] = True
    return tags


META_RE = re.compile(r'^<!--\s*quest:(.*?)-->\s*$')


def parse_meta(text):
    """`<!-- quest: id=ch07-giovanni; places=cerulean-cave; starter=any; gender=any; postgame=no -->`.

    Explicit metadata overrides what heading_tags() reads from the heading. Every key is optional.
    starter: any | Charmander[,Pikachu...] | non-Pikachu; gender: any | male | female;
    postgame / missable: yes | no; places: area slugs or names, comma-separated (none = no link); id: stable Done key.
    """
    meta = {}
    for part in text.split(';'):
        if '=' not in part:
            continue
        k, v = (x.strip() for x in part.split('=', 1))
        meta[k.lower()] = v
    return meta


def apply_meta(tags, meta, where):
    tags = dict(tags)
    if 'starter' in meta:
        v = meta['starter']
        tags.pop('starter', None)
        if v.lower() not in ('', 'any', 'all'):
            m = re.fullmatch(r'non-(\w+)', v)
            names = [x for x in STARTERS if x != m.group(1)] if m else [x.strip() for x in v.split(',')]
            bad = [x for x in names if x not in STARTERS]
            if bad:
                raise SystemExit('%s: unknown starter %s in quest metadata' % (where, bad))
            tags['starter'] = names
    if 'gender' in meta:
        v = meta['gender'].lower()
        tags.pop('gender', None)
        if v in ('male', 'female'):
            tags['gender'] = [v]
        elif v not in ('', 'any', 'either'):
            raise SystemExit('%s: unknown gender %r in quest metadata' % (where, v))
    for k in ('postgame', 'missable'):
        if k in meta:
            tags.pop(k, None)
            if meta[k].lower() in ('yes', 'true', '1'):
                tags[k] = True
    return tags


def norm_place(s):
    return s.replace('\u2019', "'").replace('\u2018', "'").strip()


# Headings about the whole game, or about places with no location page: no location link expected.
NO_PLACE = ('Romance route', 'Gym sparring partners', 'Optional strong Trainers', 'Sevii Islands', 'League HQ',
            'The Hall of Fame', 'Small extras', 'Field moves', 'Mew', 'Forest of Time', "Dialga's and Palkia's spaces",
            'Dialga, Palkia and Giratina')


class AreaIndex:
    def __init__(self, areas, aliases=None):
        self.by_slug = {a['slug']: a for a in areas}
        keys = []
        for a in areas:
            n = norm_place(a['name'])
            keys.append((n, [a]))
            short = re.sub(r' (City|Town|Island)$', '', n)
            if short != n:
                keys.append((short, [a]))
        for name, slugs in (aliases or {}).items():
            if name.startswith('_'):
                continue
            slugs = [slugs] if isinstance(slugs, str) else slugs
            found = [self.by_slug[s] for s in slugs if s in self.by_slug]
            missing = [s for s in slugs if s not in self.by_slug]
            if missing:
                print('area_aliases.json: %s -> unknown area %s' % (name, ', '.join(missing)), file=sys.stderr)
            if found:
                keys.append((norm_place(name), found))
        self.keys = sorted(keys, key=lambda k: -len(k[0]))

    def find_one(self, place):
        place = norm_place(place)
        for k, found in self.keys:
            if place == k or place.startswith(k + ' ') or place.startswith(k + ','):
                return found
        return []

    def find_all(self, place):
        """Every area named in a heading's place: "Route 16 → Cycling Road → Route 18", "Route 24 / Cerulean City"."""
        out = []
        for part in re.split(r'\s+(?:→|/)\s+', place):
            found = self.find_one(part)
            if not found:  # a list: "League gate, Mt. Silver, Route 29 and Cherrygrove"
                found = [a for sub in re.split(r',\s+|\s+and\s+', part) for a in self.find_one(sub)]
            for a in found:
                if a not in out:
                    out.append(a)
        return out

    def find(self, place):
        found = self.find_all(place)
        return found[0] if found else None


def rewrite_links(text, depth):
    """guide-relative .md links -> site-relative URLs. depth = directories below /guide/."""
    up = '../' * depth

    def repl(m):
        target, anchor = m.group(1), m.group(2) or ''
        if target == 'README.md':
            url = up or './'
        else:
            url = up + page_slug(target) + '/'
            if depth == 0:
                url = './' + url
        return '](%s%s)' % (url, anchor)
    # pictures sit beside the generated pages (see sync_images); Astro needs the explicit ./
    text = re.sub(r'\]\(images/', '](./images/', text)
    text = re.sub(r'\]\(((?:\d+-[a-z0-9-]+|known-issues|README)\.md)(#[^)]*)?\)', repl, text)
    # site reference pages: "[Move tutors](/tutors/)" means the site root, whatever the base path is.
    # Guide pages sit at /guide/ (README, depth 0) or /guide/<page>/ (depth 1).
    root = '../' * (depth + 1)
    return re.sub(r'\]\(/(?!/)([^)\s]*)\)', lambda m: '](%s%s)' % (root, m.group(1)), text)


def sync_images(check):
    """Mirror guide/images/ into OUT/images/. Returns the names that changed."""
    out = os.path.join(OUT, 'images')
    want = sorted(os.listdir(IMAGES)) if os.path.isdir(IMAGES) else []
    have = set(os.listdir(out)) if os.path.isdir(out) else set()
    changed = []
    for n in want:
        src, dst = os.path.join(IMAGES, n), os.path.join(out, n)
        if n not in have or not filecmp.cmp(src, dst, shallow=False):
            changed.append('images/' + n)
            if not check:
                os.makedirs(out, exist_ok=True)
                shutil.copyfile(src, dst + '.tmp')
                os.replace(dst + '.tmp', dst)
    for n in sorted(have - set(want)):
        changed.append('images/%s (stale)' % n)
        if not check:
            os.remove(os.path.join(out, n))
    return changed


def tag_badges(tags):
    out = []
    if 'starter' in tags:
        out.append('<span class="tag tag-starter">%s only</span>' % ' / '.join(tags['starter']))
    if 'gender' in tags:
        out.append('<span class="tag tag-gender">%s players only</span>' % ('Male' if tags['gender'] == ['male'] else 'Female'))
    if tags.get('missable'):
        out.append('<span class="tag tag-missable">Missable</span>')
    if tags.get('postgame'):
        out.append('<span class="tag tag-postgame">Post-game</span>')
    return ' '.join(out)


def fold_sources(lines):
    out = []
    for ln in lines:
        m = re.match(r'^\*Source(s)?:\*\s*(.*)$', ln)
        if m:
            out += ['<details class="tech" data-pagefind-ignore="all"><summary>Technical source (script files and flags)</summary>', '',
                    m.group(2), '', '</details>']
        else:
            out.append(ln)
    return out


def escape_mdx(text):
    """Make generated Markdown safe for MDX without changing how it renders.

    MDX reads `{`/`}` as expressions and `<` as the start of JSX, and has no HTML comments. Outside code
    spans and fenced code: `{`, `}` and a `<` that doesn't open a tag are backslash-escaped, and HTML
    comments are dropped. The tags the generator writes (<section>, <p>, <a>, <span>, <details>,
    <summary>) are valid JSX; <summary> moves to its own line below <details>.
    """
    text = re.sub(r'<!--.*?-->', '', text, flags=re.S)
    out, fence = [], None
    for ln in text.split('\n'):
        m = re.match(r'^\s*(`{3,}|~{3,})', ln)
        if fence:
            out.append(ln)
            if m and m.group(1)[0] == fence[0] and len(m.group(1)) >= len(fence):
                fence = None
            continue
        if m:
            fence = m.group(1)
            out.append(ln)
            continue
        # MDX reads a block tag followed by more on the same line as inline JSX: put <summary> on its own line
        m = re.match(r'^(\s*<details\b[^>]*>)(<summary>.*)$', ln)
        if m:
            out.append(m.group(1))
            ln = m.group(1)[:len(m.group(1)) - len(m.group(1).lstrip())] + m.group(2)
        parts = re.split(r'(`+[^`]*?`+)', ln)  # odd parts are code spans
        for i in range(0, len(parts), 2):
            parts[i] = re.sub(r'([{}])', r'\\\1', parts[i])
            parts[i] = re.sub(r'<(?![A-Za-z/])', r'\\<', parts[i])
        out.append(''.join(parts))
    return '\n'.join(out)


def strip_page_toc(lines):
    """Drop the chapter's back link and "Quests on this page" list: the site has its own navigation and contents."""
    out, i = [], 0
    while i < len(lines):
        ln = lines[i]
        if re.match(r'^\[← Guide index\]\(README\.md\)\s*$', ln):
            i += 1
            continue
        if ln.strip() == '**Quests on this page:**':
            i += 1
            while i < len(lines) and (lines[i].startswith('- ') or not lines[i].strip()):
                i += 1
            continue
        out.append(ln)
        i += 1
    return out


def gh_slug(s):
    """Heading id as Starlight (github-slugger) makes it, close enough to spot ids shared between pages."""
    s = s.strip().lower()
    s = re.sub(r'[^\w\- ]', '', s, flags=re.UNICODE)
    return s.replace(' ', '-')


def quest_headings(src):
    """(heading text, metadata) for every H2, metadata from a `<!-- quest: ... -->` line right below it."""
    lines = src.split('\n')
    out = []
    for i, ln in enumerate(lines):
        if ln.startswith('## '):
            meta = {}
            j = i + 1
            while j < len(lines) and not lines[j].strip():
                j += 1
            m = META_RE.match(lines[j].strip()) if j < len(lines) else None
            if m:
                meta = parse_meta(m.group(1))
            out.append((ln[3:].strip(), meta))
    return out


def link_place(areas, h, meta):
    if 'places' in meta:
        names = [x.strip() for x in meta['places'].split(',') if x.strip() and x.strip().lower() != 'none']
        found = []
        for n in names:
            for a in ([areas.by_slug[n]] if n in areas.by_slug else areas.find_one(n)):
                if a not in found:
                    found.append(a)
        return found, True
    if ':' not in h:
        return [], False
    return areas.find_all(h.split(':')[0]), False


def convert(fn, src, areas, shared_ids=(), report=None, force_mdx=False):
    """(file name, text) of the site page for guide/<fn>: <slug>.mdx when it has solver markers, else <slug>.md."""
    lines = src.rstrip('\n').split('\n')
    title = None
    if lines and lines[0].startswith('# '):
        title = lines[0][2:].strip()
        lines = lines[1:]
    slug = page_slug(fn)
    depth = 0 if slug == 'index' else 1
    lines = strip_page_toc(lines)
    metas = iter([m for _, m in quest_headings('\n'.join(lines))])
    body, in_quest, pending_meta, solvers = [], False, False, []
    for ln in fold_sources(lines):
        m = SOLVER_RE.match(ln)
        if m:
            name = m.group(2)
            if name not in SOLVERS:
                raise SystemExit('guide/%s: unknown solver %r (known: %s)' % (fn, name, ', '.join(sorted(SOLVERS))))
            if not in_quest:
                raise SystemExit('guide/%s: solver %r must sit inside a quest section (below an H2)' % (fn, name))
            solvers.append(name)
            body += ['', m.group(1) + SOLVER_SLOT % name, '']
            continue
        if pending_meta:
            if not ln.strip():
                continue
            pending_meta = False
            if META_RE.match(ln.strip()):
                continue
        if ln.startswith('## '):
            if in_quest:
                body += ['', '</section>', '']
            h = ln[3:].strip()
            meta = next(metas)
            where = 'guide/%s: %s' % (fn, h)
            tags = apply_meta(heading_tags(h), meta, where)
            attrs = ['data-%s="%s"' % (k, ','.join(v) if isinstance(v, list) else 'yes') for k, v in sorted(tags.items())]
            if meta.get('id'):
                attrs.append('data-quest-id="%s"' % html.escape(meta['id'], quote=True))
            if gh_slug(h) in shared_ids:
                attrs.append('data-legacy-shared="yes"')
            in_quest = slug not in ('index', 'known-issues')
            if in_quest:
                body += ['<section class="quest" %s>' % ' '.join(attrs) if attrs else '<section class="quest">', '']
            body.append(ln)
            body.append('')
            pending_meta = True
            tagline = []
            if in_quest:
                found, explicit = link_place(areas, h, meta)
                for a in found:
                    tagline.append('<a class="tag tag-place" href="%s../locations/%s/">%s</a>' % ('../' * depth, a['slug'], a['name']))
                if not found and not explicit and report is not None and not h.startswith(NO_PLACE):
                    report.append('%s: %s' % (fn, h))
            badges = tag_badges(tags) if in_quest else ''
            if badges:
                tagline.append(badges)
            if tagline:
                body += ['<p class="quest-meta">%s</p>' % ' '.join(tagline), '']
            continue
        body.append(ln)
    if in_quest:
        body += ['', '</section>']
    text = rewrite_links('\n'.join(body), depth)
    text = re.sub(r'\n{3,}', '\n\n', text)
    fm = ['---', 'title: %s' % json.dumps(title or slug), 'sidebar:', '  order: %d' % page_order(fn)]
    if slug == 'index':
        fm += ['  label: Overview']
    if fn == 'known-issues.md':
        fm += ['  label: Known issues']
    fm += ['source: guide/%s' % fn, 'editUrl: false', '---', '']
    text = text.strip('\n') + '\n'
    if not (solvers or force_mdx):
        return page_slug(fn) + '.md', '\n'.join(fm) + text
    text = escape_mdx(text)
    comps = sorted({SOLVERS[n] for n in solvers})
    head = ['import %s from \'../../../components/%s.astro\';' % (c, c) for c in comps]
    head += ['', GEN_NOTE % fn, '']
    for n in solvers:
        text = text.replace(SOLVER_SLOT % n, '<%s />' % SOLVERS[n], 1)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return page_slug(fn) + '.mdx', '\n'.join(fm) + '\n'.join(head) + text


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--unmatched', action='store_true', help='list quest headings with no location link')
    ap.add_argument('--all-mdx', action='store_true', help='test the MDX escaping: write every page as .mdx')
    a = ap.parse_args(argv)
    aliases = json.load(open(ALIASES, encoding='utf-8')) if os.path.exists(ALIASES) else {}
    areas = AreaIndex(json.load(open(AREAS, encoding='utf-8')), aliases)
    srcs = {}
    for fn in sorted(os.listdir(GUIDE)):
        if fn.endswith('.md'):
            srcs[fn] = open(os.path.join(GUIDE, fn), encoding='utf-8').read()
    # Heading ids used on more than one quest page. Old "Done" ticks were stored by bare heading id,
    # so a tick on one of these can't be told apart and is not carried over (see site/public/ohg.js).
    pages_of, quest_ids = {}, {}
    for fn, src in srcs.items():
        if page_slug(fn) in ('index', 'known-issues'):
            continue
        for h, meta in quest_headings(src):
            pages_of.setdefault(gh_slug(h), set()).add(fn)
            if meta.get('id'):
                quest_ids.setdefault(meta['id'], []).append('%s: %s' % (fn, h))
    dup = {k: v for k, v in quest_ids.items() if len(v) > 1}
    if dup:
        raise SystemExit('duplicate quest ids in <!-- quest: id=... -->: %s' % dup)
    shared = LEGACY_SHARED_IDS | {k for k, v in pages_of.items() if len(v) > 1}
    want, report = {}, []
    for fn, src in srcs.items():
        name, text = convert(fn, src, areas, shared, report, a.all_mdx)
        want[name] = text
    if a.unmatched:
        for r in report:
            print('no location link: ' + r)
        print('%d quest headings without a location link' % len(report))
    changed = []
    existing = set(os.listdir(OUT)) if os.path.isdir(OUT) else set()
    for name, text in sorted(want.items()):
        path = os.path.join(OUT, name)
        old = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if old != text:
            changed.append(name)
            if not a.check:
                os.makedirs(OUT, exist_ok=True)
                with open(path + '.tmp', 'w', encoding='utf-8') as fh:
                    fh.write(text)
                os.replace(path + '.tmp', path)
    stale = sorted(n for n in existing if n.endswith(('.md', '.mdx')) and n not in want)
    for n in stale:
        changed.append(n + ' (stale)')
        if not a.check:
            os.remove(os.path.join(OUT, n))
    changed += sync_images(a.check)
    for c in changed:
        print(('would change: ' if a.check else 'wrote: ') + 'site/src/content/docs/guide/' + c)
    print('%d guide pages, %d changed' % (len(want), len(changed)))
    return 1 if (a.check and changed) else 0


if __name__ == '__main__':
    sys.exit(main())
