#!/usr/bin/env python3
"""Local-only SIZE renderer harness; never edits source banks or production ROM.

Injects exact candidate text into trainer dialogue 0718#160 in an isolated ROM.
This exercises the real field printer, not original story scripts or UI contexts.
Use the inventory generated by size inventory audit. Native UI cases are excluded.
Each case starts at the same pre-dialogue save state. Heap checks run every 10
frames; all pages and a following normal-font sentinel are captured. Broken
Misty newline is an expected-failure negative control. Outputs contain game text
and MUST remain under ignored work/build.
"""
import argparse, hashlib, json, re, subprocess, sys, struct
from pathlib import Path
import msgtool as m

SENTINEL = 'Normal text after shout.{NEWLINE}Second normal line.'
CAPACITY = 512

def case_text(text):
    # Preserve the original bytes, including trailing page controls. Add one
    # separate ordinary-font page without adding a size reset: catches leakage.
    boundary = '' if text.endswith(('{SCROLL}', '{CLEAR}')) else '{SCROLL}'
    return text + boundary + SENTINEL + '{SCROLL}'

def pages(text):
    return re.split(r'\{(?:SCROLL|CLEAR)\}', text.rstrip().removesuffix('{SCROLL}'))

def render_text(entry):
    if entry.get('ui_case'):
        return entry['en'] if entry['en'].endswith('{SCROLL}') else entry['en']+'{SCROLL}'
    return case_text(entry['en'])

def prepare_cases(entries, mode):
    """Carry native UI lifetime and font through maximum-name variants."""
    prepared=[]
    known_ui={f'a027/0302#{i}' for i in (2,26,31,*range(166,176))}
    for source in entries:
        entry=dict(source)
        if entry['ends_in_enlarged_size']:
            if entry['ref'] not in known_ui:
                raise ValueError('No verified native UI consumer for '+entry['ref'])
            label=int(entry['ref'].split('#')[1])>=166
            entry.update(ui_case=True,harness_font=4 if label else 1,native_width=144 if label else 216)
        prepared.append(entry)
    if mode=='ordinary':return [x for x in prepared if not x['ends_in_enlarged_size']]
    ui=[x for x in prepared if x['ends_in_enlarged_size']]
    names=[dict(x,source_ref=x['ref'],ref=x['ref']+'-max-name',en=x['en'].replace('{VAR:0103:0}','WWWWWWW'),substitution='literal seven widest W glyphs replacing player-name slot; formatter itself not exercised') for x in prepared if '{VAR:0103:0}' in x['en']]
    return ui+names

def identity(path):
    h=hashlib.sha256()
    with open(path,'rb') as f:
        for block in iter(lambda:f.read(1024*1024),b''):h.update(block)
    return {'path':str(path),'sha256':h.hexdigest()}

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--rom',type=Path,required=True);p.add_argument('--inventory',type=Path,required=True)
    p.add_argument('--save',type=Path,default=Path('work/build/memcheck/trainer.sav'))
    p.add_argument('--out',type=Path,required=True);p.add_argument('--refs',default='');p.add_argument('--worker',default='');p.add_argument('--mode',choices=['ordinary','extra'],default='ordinary')
    a=p.parse_args();a.out=a.out.resolve();a.out.mkdir(parents=True,exist_ok=True)
    if not a.out.is_relative_to(Path('work/build').resolve()):p.error('Output must be under work/build')
    if a.worker:return run_worker(a)
    import ndspy.rom
    import memcheck
    script_identity=identity(__file__);inventory_identity=identity(a.inventory)
    cm=m.Charmap.load(['work/tools/charmap_en.tsv'])
    rom=ndspy.rom.NintendoDSRom.fromFile(str(a.rom));narc=m.Narc.parse(m.get_file(rom,m.MSG_NARC_PATH))
    for item in json.loads(a.inventory.read_text())['entries']:
        bank_id,entry_id=item['ref'].split('/')[1].split('#')
        _,production,_=m.decrypt_bank(narc.files[int(bank_id)])
        encoded=m.encode_text(item['en'],cm)
        assert production[int(entry_id)][:len(encoded)]==encoded, 'Inventory differs from candidate: '+item['ref']
    fonts=m.Narc.parse(m.get_file(rom,m.FONT_NARC_PATH))
    seed,strings,trailer=m.decrypt_bank(narc.files[718]);strings[160]=[0xffff]*CAPACITY
    narc.files[718]=m.encrypt_bank(seed,strings,trailer);m.set_file(rom,m.MSG_NARC_PATH,narc.build())
    testrom=a.out/'harness.nds';rom.saveToFile(str(testrom))
    # Locate exact unique encrypted bank, then modify only this fixed-size byte
    # range for each case. File table and all other ROM data remain identical.
    image=testrom.read_bytes();bank=narc.files[718];offset=image.find(bank)
    if offset<0 or image.find(bank,offset+1)>=0:raise RuntimeError('bank offset not unique')
    memcheck._check_code(a.rom)
    code=rom.loadArm9().sections[0].data
    guards={0x0200258E:'206800211df0a1fe0004000c642802d0c82804d03ee000202083a0763ae0074820830020a07635e0',0x02002674:'208b291c029012781b7860681bf03cfe',0x020208D4:'f8b5071c4d480e1c0068151c002801d1'}
    for address,expected in guards.items():
        data=bytes.fromhex(expected);assert code[address-0x02000000:address-0x02000000+len(data)]==data, f'Native hook code differs at {address:08X}'
    source_identity=identity(a.rom)
    def worker(name):
        args=[sys.executable,__file__,'--rom',str(a.rom),'--inventory',str(a.inventory),'--save',str(a.save),'--out',str(a.out),'--worker',name]
        result=subprocess.run(args,timeout=180,capture_output=True,text=True)
        (a.out/(name.replace('/','_').replace('#','_')+'.log')).write_text(result.stdout+result.stderr)
        if 'Exception ignored while calling ctypes callback' in result.stderr:raise RuntimeError('Native callback failed: '+result.stderr)
        if result.returncode:raise RuntimeError(f'worker {name} exited {result.returncode}')
    worker('bootstrap')
    entries=json.loads(a.inventory.read_text())['entries'];excluded=[x['ref'] for x in entries if x['ends_in_enlarged_size']]
    entries=prepare_cases(entries,a.mode)
    if a.refs:entries=[x for x in entries if x['ref'] in a.refs.split(',')]
    for entry in entries:
        if entry.get('ui_case'):
            codes=m.encode_text(re.sub(r'\{[^}]*\}','',entry['en']),cm)[:-1]
            font=fonts.files[entry['harness_font']];width_offset=struct.unpack_from('<I',font,4)[0]
            entry['last_glyph_width']=font[width_offset+codes[-1]-1]
            entry['static_font_width']=max(sum(font[width_offset+c-1] for c in m.encode_text(re.sub(r'\{[^}]*\}','',line),cm)[:-1]) for line in re.split(r'\{(?:NEWLINE|SCROLL|CLEAR)\}',entry['en']))
    entries.insert(0,{'ref':'control-normal','en':SENTINEL,'variable_tags':[]})
    entries.append({'ref':'negative-misty-newline','en':'{VAR:FF01:200}Misty: Stop,{NEWLINE}Gyarados!{VAR:FF01:100}','variable_tags':[]})
    report={'schema_version':1,'scope':'injected native field-printer harness; not original story encounters or Pokéathlon screens','mode':a.mode,'limitations':['Base player-name slots are empty in this trainer fixture; literal seven-W variants check maximum geometry separately, not variable formatter execution.','UI cases select the statically verified native consumer font in the field-printer template. Native UI dimensions are compared independently; the fixture window remains216x32.'],'source':source_identity,'save':identity(a.save),'excluded_native_ui':excluded,'cases':[],'expected_refs':[x['ref'] for x in entries],'script':script_identity,'inventory':inventory_identity,'code_guards_passed':True,'inventory_matches_candidate':True}
    for entry in entries:
        text=render_text(entry);units=m.encode_text(text,cm)
        if len(units)>CAPACITY:raise ValueError('harness capacity exceeded')
        strings[160]=units+[0xffff]*(CAPACITY-len(units));encoded=m.encrypt_bank(seed,strings,trailer)
        assert len(encoded)==len(bank)
        with testrom.open('r+b') as f:f.seek(offset);f.write(encoded)
        (a.out/'current-case.json').write_text(json.dumps(entry))
        worker(entry['ref'])
        case=json.loads((a.out/'current-result.json').read_text())
        if entry['ref']=='control-normal':baseline=case['screenshots'][-1]['text_crop_sha256']
        if not entry['ref'].startswith('negative-') and not entry.get('ui_case'):
            case['sentinel_matches_normal_control']=case['screenshots'][-1]['text_crop_sha256']==baseline
            if not case['sentinel_matches_normal_control']:case['status']='incomplete'
        report['cases'].append(case)
        (a.out/'report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n')
        print(json.dumps({'ref':entry['ref'],'status':case['status'],'corrupt':case['corrupt']}),flush=True)
    report['source_unchanged']=identity(a.rom)==source_identity
    report['script_unchanged']=identity(__file__)==script_identity
    report['inventory_unchanged']=identity(a.inventory)==inventory_identity
    report['coverage_complete']=[x['ref'] for x in report['cases']]==report['expected_refs']
    (a.out/'report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n')
    return 0 if report['source_unchanged'] and report['script_unchanged'] and report['inventory_unchanged'] and report['coverage_complete'] and all(x['status'] in ('pass','expected-failure') for x in report['cases']) else 1

def run_worker(a):
    import memcheck
    from desmume.emulator import DeSmuME
    from desmume.controls import Keys,keymask
    testrom=a.out/'harness.nds';state=a.out/'before-talk.dst'
    if a.worker=='bootstrap':
        e=DeSmuME();e.open(str(testrom));e.backup.import_file(str(a.save.resolve()),524288);e.reset()
        def rawstep(n):
            for _ in range(n):e.cycle(with_joystick=False)
        def rawpress(k):
            mask=keymask(getattr(Keys,'KEY_'+k));e.input.keypad_add_key(mask);rawstep(6);e.input.keypad_rm_key(mask)
        rawstep(2400);rawpress('START');rawstep(400);rawpress('A');rawstep(300);rawpress('A');rawstep(300)
        state=a.out/'before-talk.dst';e.savestate.save_file(str(state));e.screenshot().save(a.out/'before-talk.png')
        e.destroy()
        return 0
    entry=json.loads((a.out/'current-case.json').read_text());ref=entry['ref'];text=render_text(entry)
    e=DeSmuME();e.open(str(testrom));e.savestate.load_file(str(state));pr=memcheck.Probe(e);pr.armed=True
    case={'ref':ref,'text':entry['en'],'source_ref':entry.get('source_ref',ref),'page_count':len(pages(text)),'screenshots':[],'variable_tags':entry.get('variable_tags',[]),'status':'incomplete','ui_case':entry.get('ui_case',False),'substitution':entry.get('substitution'),'native_width':entry.get('native_width'),'harness_font':entry.get('harness_font')}
    glyphs=[];size_events=[];printer_starts=[]
    def glyph(addr,size):
        ptr=e.memory.register_arm9.r4;u=e.memory.unsigned
        glyphs.append({'frame':pr.frame,'printer':ptr,'x':u.read_byte(ptr+12),'y':u.read_byte(ptr+14),'size_word':u.read_short(ptr+24),'font':u.read_byte(ptr+9)})
    def size_event(addr,size):
        ptr=e.memory.register_arm9.r4;u=e.memory.unsigned
        size_events.append({'frame':pr.frame,'printer':ptr,'size_word':u.read_short(ptr+24)})
    def printer_start(addr,size):
        ptr=e.memory.register_arm9.r0
        if entry.get('ui_case') and pr.frame<20 and e.memory.unsigned.read_byte(ptr+9)==1:e.memory.write_byte(ptr+9,entry['harness_font'])
        printer_starts.append({'frame':pr.frame,'template':ptr,'size_word':e.memory.unsigned.read_short(ptr+24)})
    e.memory.register_exec(0x02002680,glyph)
    e.memory.register_exec(0x020025B4,size_event)
    e.memory.register_exec(0x020025AA,size_event)
    e.memory.register_exec(0x020208D4,printer_start)
    def step(n):
        for _ in range(n):
            e.cycle(with_joystick=False);pr.frame+=1
            if pr.frame%10==0 and pr.corrupt is None:
                bad=pr.heap_walk()
                if bad:pr.corrupt=(pr.frame,bad)
    def press(k):
        mask=keymask(getattr(Keys,'KEY_'+k));e.input.keypad_add_key(mask);step(6);e.input.keypad_rm_key(mask)
    safe=ref.replace('/','_').replace('#','_');directory=a.out/safe;directory.mkdir(exist_ok=True)
    for i,page in enumerate(pages(text)):
        page_start=pr.frame;glyph_start=len(glyphs)
        press('A');step(240)
        path=directory/f'page-{i+1:02d}.png';e.screenshot().save(path)
        crop=e.screenshot().crop((12,153,236,183)).convert('RGB')
        case['screenshots'].append({'page':i+1,'path':str(path),'expected':page,'sentinel':i==len(pages(text))-1,'frame_start':page_start,'frame_end':pr.frame,'glyphs':glyphs[glyph_start:],'text_crop_sha256':hashlib.sha256(crop.tobytes()).hexdigest()})
        if pr.corrupt or pr.nullw:break
    if not pr.corrupt:
        press('A');step(900 if entry.get('ui_case') else 120);press('X');step(90)
        path=directory/'after-menu.png';e.screenshot().save(path);case['after_menu']=str(path)
    case.update(minspare=pr.minspare,glyphs=glyphs,size_events=size_events,printer_starts=printer_starts,heap_checks=pr.heap_checks,heap_table_errors=pr.heap_table_errors,corrupt=pr.corrupt,allocation_failures=pr.fails,null_writes=pr.nullw,message_loads=pr.message_loads)
    failure=bool(pr.corrupt or pr.fails or pr.nullw or pr.heap_table_errors)
    expected_sizes=[65532 if int(x)==200 else 0 for x in re.findall(r'\{VAR:FF01:(\d+)\}',entry['en'])]
    observed_sizes=[x['size_word'] for x in size_events]
    sentinel=case['screenshots'][-1]
    case['assertions']={'heap_observations':pr.heap_checks>0 and bool(pr.minspare),'all_pages_have_glyphs':len(case['screenshots'])==len(pages(text)) and all(x['glyphs'] for x in case['screenshots']),'size_sequence_matches':observed_sizes==expected_sizes,'sentinel_drawn_normal':sentinel['sentinel'] and bool(sentinel['glyphs']) and all(g['size_word']==0 for g in sentinel['glyphs']),'enlarged_glyphs_at_top':all(g['y']==0 for g in glyphs if g['size_word']==65532),'fresh_printers_normal':bool(printer_starts) and all(x['size_word']==0 for x in printer_starts)}
    if entry.get('ui_case'):
        following=[g for g in glyphs if g['frame']>sentinel['frame_end']]
        later_starts=[x for x in printer_starts if x['frame']>sentinel['frame_end']]
        case['assertions'].pop('sentinel_drawn_normal')
        case['assertions']['following_printer_normal']=bool(later_starts) and bool(following) and all(g['size_word']==0 for g in following)
        case['assertions']['native_font_used']=all(g['font']==entry['harness_font'] for g in glyphs if g['size_word']==65532)
        enlarged=[g for g in glyphs if g['size_word']==65532]
        extent=max((g['x'] for g in enlarged),default=0)-min((g['x'] for g in enlarged),default=0)+entry['last_glyph_width']
        case['rendered_advance_extent']=extent;case['static_font_width']=entry['static_font_width']
        case['fixture_window_px']=[216,32];case['native_window_px']=[entry['native_width'],32]
        case['assertions']['native_width_bound']=bool(enlarged) and extent<=entry['native_width'] and entry['static_font_width']<=entry['native_width']
    case['expected_sizes']=expected_sizes;case['observed_sizes']=observed_sizes
    case['status']=('expected-failure' if pr.corrupt else 'negative-control-missed') if ref.startswith('negative-') else ('fail' if failure else ('pass' if all(case['assertions'].values()) else 'incomplete'))
    e.destroy();(a.out/'current-result.json').write_text(json.dumps(case,indent=2))
    return 0
if __name__=='__main__':raise SystemExit(main())
