import test from 'node:test';
import assert from 'node:assert/strict';
import {loadBundledOriginData} from '../dist/core/bundled-data.js';
import {speciesInfo,FORM_CHOICES,personalIndex} from '../dist/core/species-info.js';
import {createPokemon,emptyPartyRecord,decodePokemon,patchPokemonMetadata,readPokemonMetadata,patchPokemonExperience,clonePokemon,patchPokemonOT} from '../dist/core/pokemon.js';
import {crc16,readSave,readStorage} from '../dist/core/save.js';
import {transferPokemon,placePokemon,fillBox,sortBox,batchBox,exportPokemonFile,importPokemonFile,searchPokemon} from '../dist/core/operations.js';
import {exportShowdown,importShowdown} from '../dist/core/showdown.js';
import {patchTrainerProfile,readTrainer} from '../dist/core/trainer.js';
import {readPokedex,patchPokedex,completePokedex} from '../dist/core/pokedex.js';
const data=loadBundledOriginData();
function mon(id=1,form=0){const info=speciesInfo(id,form);return createPokemon(emptyPartyRecord(),{speciesId:id,form,level:50,nature:3,shiny:false,gender:info.genderRatio===255?'genderless':info.genderRatio===254?'female':'male',ability:info.abilities[0],abilitySlot:0,ivs:{hp:31,attack:20,defense:19,speed:18,spAttack:17,spDefense:16},moves:[{id:33,pp:35}],name:data.catalog.getSpecies(id).name,genderRatio:info.genderRatio,baseFriendship:info.baseFriendship,personal:data.getPersonal(id,form)});}
function save(){const bytes=new Uint8Array(0x80000),dv=new DataView(bytes.buffer);for(const base of [0,0x40000]){dv.setUint32(base+0x90,6,true);dv.setUint32(base+0x94,2,true);bytes.set(mon(),base+0x98);bytes.set(mon(571,1),base+0x98+236);dv.setUint32(base+0x13a8,0xbeefcafe,true);for(let box=0;box<24;box++)for(let slot=0;slot<30;slot++)bytes.set(emptyPartyRecord().slice(0,136),base+0xf800+box*0x1000+slot*136);for(const [offset,size,id] of [[base,0xf7cc,0],[base+0xf800,0x18408,1]]){const footer=offset+size-16;dv.setUint32(footer,base?1:2,true);dv.setUint32(footer+4,size,true);dv.setUint32(footer+8,0x20060623,true);dv.setUint16(footer+12,id,true);dv.setUint16(footer+14,crc16(bytes.subarray(offset,footer)),true);}}return bytes;}
for(const size of [136,236])test(`metadata fields round-trip and preserve identity/training/tail (${size})`,()=>{const input=mon().slice(0,size),before=decodePokemon(input),changes={nickname:'Éclair',nicknamed:true,friendship:255,markings:63,language:2,originGame:7,otGender:'female',ball:24,metLevel:45,metLocation:60000,eggLocation:3000,metDate:'2024-02-29',eggDate:'2020-06-01',encounterType:9,fateful:true,ribbons:[0xffffffff,0x87654321,0x12345678]};const result=patchPokemonMetadata(input,changes),after=decodePokemon(result);assert.deepEqual(readPokemonMetadata(result),changes);for(const key of ['pid','speciesId','gender','form','moves','ivs','evs','experience','nature','shiny','ability','heldItem','otName','tid','sid','party'])assert.deepEqual(after[key],before[key]);assert.deepEqual(result.slice(136),input.slice(136));assert.deepEqual(readPokemonMetadata(input).ribbons,[0,0,0]);for(const invalid of [{metDate:'2023-02-29'},{nickname:'too long nickname'},{friendship:256},{ball:0},{metLevel:101},{markings:64},{ribbons:[-1,0,0]}])assert.throws(()=>patchPokemonMetadata(input,invalid));});
test('experience uses native growth curve and recalculates party level',()=>{const record=mon(),personal=data.getPersonal(1,0),result=patchPokemonExperience(record,personal.growthThresholds[75]+1,personal);assert.equal(decodePokemon(result).party.level,75);assert.equal(decodePokemon(result).experience,personal.growthThresholds[75]+1);assert.deepEqual(decodePokemon(result).ivs,decodePokemon(record).ivs);assert.throws(()=>patchPokemonExperience(record,-1,personal));});
test('cloning rekeys records and preserves metadata, stats, gender, nature and shiny',()=>{for(const size of [136,236]){const original=patchPokemonMetadata(mon(571,1),{nickname:'Ghost',nicknamed:true,friendship:230}).slice(0,size),before=decodePokemon(original),copy=clonePokemon(original),after=decodePokemon(copy);assert.notEqual(after.pid,before.pid);assert.deepEqual({...after,pid:before.pid},before);assert.deepEqual(readPokemonMetadata(copy),readPokemonMetadata(original));const shiny=patchPokemonOT(original,{tid:1,sid:1^(before.pid>>>16)^(before.pid&65535)});assert.equal(decodePokemon(clonePokemon(shiny)).naturalShiny,true);}});
test('move/copy/clone operations preserve mirrors and restore boxed party stats',()=>{const original=save(),originalCopy=original.slice();let result=transferPokemon(original,{kind:'party',slot:1},{kind:'pc',box:0,slot:0},'move',data);assert.equal(readSave(result).partyCount,1);assert.equal(decodePokemon(readStorage(result).boxes[0][0]).form,1);assert.deepEqual(result.slice(0x40000),original.slice(0x40000));assert.deepEqual(original,originalCopy);result=transferPokemon(result,{kind:'pc',box:0,slot:0},{kind:'party',slot:1},'move',data);assert.equal(readSave(result).partyCount,2);assert.equal(decodePokemon(readSave(result).partyRecords[1]).party.level,50);assert.equal(decodePokemon(readStorage(result).boxes[0][0]).speciesId,0);result=transferPokemon(result,{kind:'party',slot:0},{kind:'pc',box:1,slot:0},'clone',data);assert.notEqual(decodePokemon(readStorage(result).boxes[1][0]).pid,decodePokemon(readSave(result).partyRecords[0]).pid);assert.throws(()=>transferPokemon(result,{kind:'party',slot:0},{kind:'pc',box:1,slot:0},'move',data));});
test('box fill gives distinct PIDs; sort and batch keep occupied records',()=>{let result=placePokemon(save(),{kind:'pc',box:0,slot:0},mon(571,1),data);const occupied=readStorage(result).boxes[0][0];result=fillBox(result,0,mon());let records=readStorage(result).boxes[0];assert.deepEqual(records[0],occupied);assert.equal(new Set(records.map(r=>decodePokemon(r).pid)).size,30);assert.equal(records.slice(1).filter(r=>decodePokemon(r).shiny).length,1);assert.throws(()=>fillBox(result,0,mon()));result=sortBox(result,0);assert.equal(decodePokemon(readStorage(result).boxes[0].at(-1)).speciesId,571);result=batchBox(result,0,r=>patchPokemonMetadata(r,{friendship:255}));assert.ok(readStorage(result).boxes[0].every(r=>readPokemonMetadata(r).friendship===255));assert.equal(searchPokemon(result,'Zoroark',data).length,2);});
test('Origin file and Showdown imports round-trip native forms and reject unsupported input',()=>{const record=patchPokemonMetadata(mon(571,1),{nickname:'Ghost',nicknamed:true,friendship:222});assert.deepEqual(importPokemonFile(exportPokemonFile(record),data),record);assert.throws(()=>importPokemonFile('{"format":"pk4"}',data));const set=exportShowdown(record,data),copy=importShowdown(set,record,data)[0],before=decodePokemon(record),after=decodePokemon(copy);for(const key of ['speciesId','form','gender','nature','ability','shiny','ivs','evs','nickname','experience'])assert.deepEqual(after[key],before[key]);assert.equal(readPokemonMetadata(copy).friendship,222);assert.throws(()=>importShowdown(set+'\nTera Type: Fire',record,data));});
test('all exposed forms resolve to distinct verified native personal rows',()=>{assert.ok(FORM_CHOICES.length>16);for(const choice of FORM_CHOICES){assert.equal(personalIndex(choice.speciesId,choice.form),choice.id);const record=mon(choice.speciesId,choice.form);assert.equal(decodePokemon(record).form,choice.form);assert.equal(decodePokemon(importPokemonFile(exportPokemonFile(record),data)).speciesId,choice.speciesId);}});
test('trainer profile edits preserve party and backup bytes',()=>{const input=save(),before=readSave(input).partyRecords,output=patchTrainerProfile(input,{name:'May',gender:'female',tid:12345,sid:54321,language:2}),profile=readTrainer(output);assert.equal(profile.name,'May');assert.equal(profile.gender,'female');assert.equal(profile.tid,12345);assert.equal(profile.sid,54321);assert.deepEqual(readSave(output).partyRecords,before);assert.deepEqual(output.slice(0x40000),input.slice(0x40000));assert.throws(()=>patchTrainerProfile(input,{name:'12345678'}));});
test('native Pokédex flags preserve padding, alternate records and backups',()=>{const original=save();let result=patchPokedex(original,1025,{caught:true});assert.equal(readPokedex(result).caught[1024],true);assert.equal(readPokedex(result).seen[1024],true);const changed=[];for(let i=0;i<original.length;i++)if(original[i]!==result[i])changed.push(i);assert.ok(changed.every(i=>[0x13a8+4+128,0x13a8+0xcc+128,0x1718,0x1719,0xf7cc-2,0xf7cc-1].includes(i)));result=patchPokedex(result,1025,{seen:false});assert.equal(readPokedex(result).caught[1024],false);result=completePokedex(result);assert.equal(readPokedex(result).seenCount,1025);assert.equal(readPokedex(result).caughtCount,1025);assert.deepEqual(result.slice(0x40000),original.slice(0x40000));assert.throws(()=>patchPokedex(result,1026,{seen:true}));});

import {patchGeneralRegion} from '../dist/core/save.js';
import {readMysteryGifts,patchGiftReceived,exportWonderCard,importWonderCard,removePendingGift,removeWonderCard} from '../dist/core/mystery-gift.js';
test('native Wonder Card imports link pending gifts and repair both CRCs',()=>{const input=save(),card=new Uint8Array(0x358),dv=new DataView(card.buffer);dv.setUint16(0,3,true);dv.setUint32(4,1,true);dv.setUint16(0x150,123,true);card[0x152]=9;let result=importWonderCard(input,JSON.stringify({format:'origin-heartgold-wonder-card',version:1,bytes:[...card]}),data);let state=readMysteryGifts(result);assert.equal(state.cards[0].id,123);assert.equal(state.cards[0].tag,3);assert.equal(state.gifts[0].tag,3);assert.equal(state.gifts[0].cardSlot,0);assert.equal(state.received[123],true);assert.deepEqual(JSON.parse(exportWonderCard(result,0)).bytes,[...card]);assert.equal(new DataView(result.buffer).getUint16(0xb560,true),crc16(result.slice(0x9ee0,0xb560)));assert.deepEqual(result.slice(0x40000),input.slice(0x40000));assert.throws(()=>importWonderCard(result,exportWonderCard(result,0),data));const cleared=removePendingGift(result,0);assert.equal(readMysteryGifts(cleared).gifts[0].tag,0);result=removeWonderCard(result,0);state=readMysteryGifts(result);assert.equal(state.cards[0].tag,0);assert.equal(state.gifts[0].tag,0);assert.equal(state.received[123],false);result=patchGiftReceived(result,2047,true);assert.equal(readMysteryGifts(result).received[2047],true);assert.throws(()=>patchGiftReceived(result,2048,true));card[0]=15;assert.throws(()=>importWonderCard(input,JSON.stringify({format:'origin-heartgold-wonder-card',version:1,bytes:[...card]}),data));});
test('general mutations repair the native inner CRC without changing padding',()=>{const input=save();for(const [start,size,offset] of [[0,0x5c,0x34],[0x60,0x2c,0x80],[0x90,0x5b0,0x94],[0x644,0x864,0x648],[0x13a8,0x370,0x13ac]]){const result=patchGeneralRegion(input,offset,Uint8Array.of(input[offset]^1));assert.equal(new DataView(result.buffer).getUint16(start+size,true),crc16(result.slice(start,start+size)));assert.deepEqual(result.slice(start+size+2,start+size+4),input.slice(start+size+2,start+size+4));}});

import {pokemonChecks} from '../dist/core/operations.js';
test('Origin encounter checks identify contradictory dates and met levels',()=>{const record=mon(),metadata=readPokemonMetadata(record),problems=pokemonChecks(decodePokemon(record),{...metadata,metLevel:60,eggDate:'2025-01-02',metDate:'2025-01-01',eggLocation:0},50);assert.ok(problems.some(p=>p.includes('Met level')));assert.ok(problems.some(p=>p.includes('later')));assert.ok(problems.some(p=>p.includes('egg location')));});
